CIRCLES_LIST = {
  "BIHAR and JHARKHAND" => {},
  "MUMBAI" => {"Mumbai" => 3},
  "MAHARASHTRA" => {"Mumbai" => 3, "Pune" => 5},
  "TAMILNADU" => {"Chennai" => 7},
  "ANDHRA PRADESH" => {"Hyderabad" => 6},
  "PUNJAB" => {"Chandigarh" => 12, "Ludhiana" => 20},
  "NORTH EAST" => {},
  "UTTAR PRADESH (E)" => {"Lucknow" => 8},
  "UTTAR PRADESH (W) and UTTARAKHAND" => {"Lucknow" => 8},
  "KARNATAKA" => {"Bangalore" => 4},
  "MADHYA PRADESH and CHHATISGARH" => {"Indore" => 14},
  "KERALA" => {},
  "HARYANA" => {},
  "GUJARAT" => {"Ahmedabad" => 11},
  "ORISSA" => {},
  "WEST BENGAL" => {"Kolkata" => 2},
  "CHENNAI" => {},
  "KOLKATA" => {"Kolkata" => 2},
  "JAMMU_KASHMIR" => {},
  "ASSAM" => {},
  "DELHI" => {"Delhi" => 1},
  "RAJASTHAN" => {"Jaipur" => 10},
  "HIMACHAL PRADESH" => {},
}
