CITIES_AUX = {
  "1" => "Delhi",
  "2" => "Kolkata",
  "3" => "Mumbai",
  "4" => "Bangalore",
  "5" => "Pune",
  "6" => "Hyderabad",
  "7" => "Chennai",
  "8" => "Lucknow",
  "10" => "Jaipur",
  "11" => "Ahmedabad",
  "12" => "Chandigarh",
  "14" => "Indore",
  "20" => "Ludhiana",
}
